---
- name: Ensure created staging area
  file:
    path: "{{ releases_path }}/.pool"
    owner: "{{ releases_owner }}"
    group: "{{ releases_group }}"
    mode: 0755
    state: directory

- name: Ensure files exist in staging area
  copy:
    src: "{{ item }}"
    dest: "{{ releases_path }}/.pool/"
    owner: "{{ releases_owner }}"
    group: "{{ releases_group }}"
    mode: 0644
  loop: "{{ query('fileglob', releases_pattern) }}"
  loop_control:
    label: "{{ item | basename }}"
  register: releases_prepare_upload

- name: Ensure checksums exist in staging area
  lineinfile:
    path: "{{ releases_path }}/.pool/{{ item.1 | upper }}S"
    regexp: " *{{ item.0.item | basename }}$"
    line: >-
      {%- if item[0][item.1] is defined -%}
      {{ item[0][item.1] }} *{{ item.0.item | basename }}
      {%- elif item.1 == 'sha1sum' -%}
      {{ item[0]["checksum"] }} *{{ item.0.item | basename }}
      {%- else -%}
      {{ lookup('pipe', item.1 + ' -b ' + item.0.item) |
      regex_findall('([a-z0-9]{32,64})') | first }} *{{ item.0.item | basename }}
      {%- endif -%}
    owner: "{{ releases_owner }}"
    group: "{{ releases_group }}"
    mode: 0644
    create: true
  loop: "{{ releases_prepare_upload.results | selectattr('dest', 'search', 'iso$') | product(['md5sum', 'sha1sum', 'sha256sum']) | list }}"
  loop_control:
    label: "{{ item.1 | upper }}: {{ item.0.item | basename }}"
  when: not ansible_check_mode
